"""add certificate_settings table

Revision ID: 0242a267489d
Revises: 
Create Date: 2026-04-14 16:12:02.794421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0242a267489d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('title_text', sa.String(length=200), nullable=True),
    sa.Column('default_course_summary', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('year_of_study', sa.String(length=20), nullable=True),
    sa.Column('program_start_date', sa.Date(), nullable=True),
    sa.Column('program_end_date', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('responsibility', sa.String(length=255), nullable=True),
    sa.Column('year_of_employment', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('staff_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(length=100), nullable=False),
    sa.Column('student_last_name', sa.String(length=100), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_summary', sa.Text(), nullable=True),
    sa.Column('year_of_study', sa.String(length=20), nullable=True),
    sa.Column('verification_code', sa.String(length=50), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_logs')
    op.drop_table('certificates')
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('certificate_settings')
    # ### end Alembic commands ###
