"""add course_name to certificate_settings

Revision ID: 05bb4db84e72
Revises: 8984e9aabce6
Create Date: 2026-06-19 09:43:35.195505

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '05bb4db84e72'
down_revision = '8984e9aabce6'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Add column as nullable
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.String(length=255), nullable=True))

    # 2. Set a default value for all existing rows
    # (Assume a single row exists; if you have multiple, they'll all get 'Default')
    op.execute("UPDATE certificate_settings SET course_name = 'Default' WHERE course_name IS NULL")

    # 3. Alter column to be non-nullable and add unique constraint
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.alter_column('course_name', nullable=False)
        batch_op.create_unique_constraint('uq_certificate_settings_course_name', ['course_name'])

def downgrade():
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_certificate_settings_course_name', type_='unique')
        batch_op.drop_column('course_name')












# """add course_name to certificate_settings

# Revision ID: 05bb4db84e72
# Revises: 8984e9aabce6
# Create Date: 2026-06-19 09:43:35.195505

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '05bb4db84e72'
# down_revision = '8984e9aabce6'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('course_name', sa.String(length=255), nullable=False))
#         batch_op.create_unique_constraint(None, ['course_name'])

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='unique')
#         batch_op.drop_column('course_name')

#     # ### end Alembic commands ###
