"""store images as blobs

Revision ID: 24e59d3ca6cd
Revises: 0242a267489d
Create Date: 2026-04-14 17:32:20.450659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e59d3ca6cd'
down_revision = '0242a267489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signature_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('signature_mime', sa.String(length=100), nullable=True))
        batch_op.drop_column('logo_url')
        batch_op.drop_column('signature_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('signature_mime')
        batch_op.drop_column('signature_data')
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo_data')

    # ### end Alembic commands ###
