"""add signature names

Revision ID: 3d6fb1ef6b2b
Revises: 8d091fd627ad
Create Date: 2026-04-15 10:10:02.993779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6fb1ef6b2b'
down_revision = '8d091fd627ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature2_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_column('signature2_name')
        batch_op.drop_column('signature_name')

    # ### end Alembic commands ###
