"""add new column for certificate duration

Revision ID: 46648c530842
Revises: e4f66409de05
Create Date: 2026-04-17 10:27:14.178938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46648c530842'
down_revision = 'e4f66409de05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Certificate_duration_text', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_column('Certificate_duration_text')

    # ### end Alembic commands ###
