"""add new column for full name on certificate and student tables

Revision ID: 73045d6ae976
Revises: 46648c530842
Create Date: 2026-04-17 10:39:46.139518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73045d6ae976'
down_revision = '46648c530842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_full_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('student_full_name')

    # ### end Alembic commands ###
