"""add student_id column (nullable)

Revision ID: 8984e9aabce6
Revises: d0c5cf61c18b
Create Date: 2026-04-17 14:23:23.003055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8984e9aabce6'
down_revision = 'd0c5cf61c18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
