"""add second signature

Revision ID: 8d091fd627ad
Revises: 24e59d3ca6cd
Create Date: 2026-04-15 08:58:17.886728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d091fd627ad'
down_revision = '24e59d3ca6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature2_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('signature2_mime', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_column('signature2_mime')
        batch_op.drop_column('signature2_data')

    # ### end Alembic commands ###
