"""add new column for signature holder position

Revision ID: d0c5cf61c18b
Revises: 73045d6ae976
Create Date: 2026-04-17 11:19:19.601181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c5cf61c18b'
down_revision = '73045d6ae976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_holder_position', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('signature2_holder_position', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_column('signature2_holder_position')
        batch_op.drop_column('signature_holder_position')

    # ### end Alembic commands ###
