"""add two more logos

Revision ID: e4f66409de05
Revises: 3d6fb1ef6b2b
Create Date: 2026-04-15 11:08:15.466245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f66409de05'
down_revision = '3d6fb1ef6b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo2_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo2_mime', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo3_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo3_mime', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_settings', schema=None) as batch_op:
        batch_op.drop_column('logo3_mime')
        batch_op.drop_column('logo3_data')
        batch_op.drop_column('logo2_mime')
        batch_op.drop_column('logo2_data')

    # ### end Alembic commands ###
